----------------------- VALIDAR CLIENTE --------------------------------
		
CREATE OR REPLACE FUNCTION T_VALIDAR_CLIENTE()
RETURNS TRIGGER AS $$
	BEGIN
		PERFORM VALIDAR_EMAIL(NEW.EMAIL);
		PERFORM VALIDAR_TELEFONE(NEW.TELEFONE);
		PERFORM VALIDAR_CEP(NEW.CEP);
		PERFORM VALIDAR_CPF(NEW.CPF);
		RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';


CREATE OR REPLACE TRIGGER TRIGGER_VALIDAR_CLIENTE 
BEFORE INSERT OR UPDATE ON CLIENTE
FOR EACH ROW
EXECUTE PROCEDURE T_VALIDAR_CLIENTE


---------------------- VALIDAR FORNECEDOR -------------------------------

CREATE OR REPLACE FUNCTION T_VALIDAR_FORNECEDOR()
RETURNS TRIGGER AS $$
	BEGIN
		PERFORM VALIDAR_EMAIL(NEW.EMAIL);
		PERFORM VALIDAR_TELEFONE(NEW.TELEFONE);
		PERFORM VALIDAR_CEP(NEW.CEP);
		
		IF VERIFICAR_CNPJ_CPF(NEW.CPF) THEN
			PERFORM VALIDAR_CPF(NEW.CPF);
		ELSE
			PERFORM VALIDAR_CNPJ(NEW.CNPJ);
		END IF;
		
		RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';


CREATE OR REPLACE TRIGGER TRIGGER_VALIDAR_FORNECEDOR
BEFORE INSERT OR UPDATE ON FORNECEDOR
FOR EACH ROW
EXECUTE PROCEDURE T_VALIDAR_FORNECEDOR

